# Generated by Django 4.2.6 on 2023-10-11 09:11

import django.contrib.gis.db.models.fields
import django.contrib.postgres.operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('points', '0001_initial'), ('points', '0002_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.CreateExtension(
            name='postgis',
        ),
        migrations.CreateModel(
            name='PointsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obj_id', models.IntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LinesModel',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_point', to='points.pointsmodel')),
                ('to_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_point', to='points.pointsmodel')),
            ],
        ),
    ]
