# Generated by Django 3.1.1 on 2020-09-28 19:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_starts_from', to='points.points')),
                ('to_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_ends_with', to='points.points')),
            ],
        ),
    ]
