# Generated by Django 3.1.1 on 2020-09-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='from_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_point', to='points.points'),
        ),
        migrations.AlterField(
            model_name='lines',
            name='to_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_point', to='points.points'),
        ),
    ]
