# Generated by Django 3.1.1 on 2020-09-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20200928_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinesModel',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Points',
            new_name='PointsModel',
        ),
        migrations.DeleteModel(
            name='Lines',
        ),
        migrations.AddField(
            model_name='linesmodel',
            name='from_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_point', to='points.pointsmodel'),
        ),
        migrations.AddField(
            model_name='linesmodel',
            name='to_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_point', to='points.pointsmodel'),
        ),
    ]
