# Generated by Django 3.1.1 on 2020-09-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20200929_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsmodel',
            name='obj_id',
            field=models.IntegerField(default=0),
        ),
    ]
